__Assignment3__

**Q7. Feature Engineering for Model Improvement**

Context: Raw data is rarely useful—features must be created.

Dataset: Titanic

Tasks:

1. Create: family_size = sibsp + parch + 1
2. Create: is_alone (binary feature)
3. Compute survival rate by is_alone   
4. Explain: Why engineered features improve ML models

In [7]:
#1. Create: family_size = sibsp + parch + 1
import seaborn as sns
import pandas as pd
titanicDataSet = sns.load_dataset("titanic")
#titanicDataSet.head(10)
# New feature family_size
titanicDataSet["family_size"] = (titanicDataSet["sibsp"]+titanicDataSet["parch"] + 1)
titanicDataSet.head(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family_size
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,2
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,2
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,1
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,2
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1

In [20]:
#2. Create: is_alone (binary feature)
titanicDataSet["family_size"] = (titanicDataSet["sibsp"]+titanicDataSet["parch"] + 1)
titanicDataSet["is_alone"] = (titanicDataSet["family_size"] == 1)
titanicDataSet.head(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family_size,is_alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,2,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,2,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,1,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,2,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1,True

In [33]:
#3. Compute survival rate by is_alone
titanicDataSet["family_size"] = (titanicDataSet["sibsp"]+titanicDataSet["parch"] + 1)
titanicDataSet["is_alone"] = (titanicDataSet["family_size"] == 1)

survival_rate_by_is_alone = (titanicDataSet.groupby("is_alone")["survived"].mean())
print(survival_rate_by_is_alone)

is_alone
False    0.505650
True     0.303538
Name: survived, dtype: float64

In [ ]:
# 4. Explain: Why engineered features improve ML models
The purpose of creating feature engineering fields is to improve the machine learning models as they convert the raw
data to meaningful data or patters which is easy for model to learn or improve accuracy.