__Assignment3__

**Q13. Custom Feature Transformation using apply()**

Context: Real ML requires custom logic transformation.

Dataset: Titanic

Tasks:

1. Create age_group: Child / Adult / Senior
2. Use .apply()
3. Compute survival rate per group
4. Interpret: Which segment has highest survival likelihood

In [19]:
#1. Create age_group: Child / Adult / Senior

import pandas as pd

df = pd.read_csv("titanic.csv")

#df.columns = df.columns.str.lower()
df["age"] = df["age"].fillna(df["age"].median())

df["age_group"] = pd.cut(
    df["age"],
    bins=[0, 18, 60, df["age"].max()],
    labels=["Child", "Adult", "Senior"],
    right=False
)

df[["age", "age_group"]].head(10)

    age age_group
0  22.0     Adult
1  38.0     Adult
2  26.0     Adult
3  35.0     Adult
4  35.0     Adult
5  28.0     Adult
6  54.0     Adult
7   2.0     Child
8  27.0     Adult
9  14.0     Child

In [20]:
#2 Use .apply()

import pandas as pd

df = pd.read_csv("titanic.csv")
df.columns = df.columns.str.lower()
df["age"] = df["age"].fillna(df["age"].median())
df["age_group"] = df["age"].apply(lambda x: "Child" if x < 18 else ("Adult" if x < 60 else "Senior"))
df[["age", "age_group"]].head(10)

    age age_group
0  22.0     Adult
1  38.0     Adult
2  26.0     Adult
3  35.0     Adult
4  35.0     Adult
5  28.0     Adult
6  54.0     Adult
7   2.0     Child
8  27.0     Adult
9  14.0     Child

In [23]:
#3. Compute survival rate per group

import pandas as pd

# Load dataset
df = pd.read_csv("titanic.csv")

# Normalize column names (good practice)
df.columns = df.columns.str.lower()

# Handle missing age values
df["age"] = df["age"].fillna(df["age"].median())

# Create age_group using pd.cut (from previous task)
df["age_group"] = pd.cut(
    df["age"],
    bins=[0, 18, 60, df["age"].max()],
    labels=["Child", "Adult", "Senior"],
    right=False
)

# Compute survival rate per age group
survivalRate = df.groupby("age_group")["survived"].mean()
print(survivalRate)

age_group
Child     0.539823
Adult     0.364362
Senior    0.240000
Name: survived, dtype: float64

C:\Users\gk250115\AppData\Local\Temp\ipykernel_14728\1521110526.py:23: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  survivalRate = df.groupby("age_group")["survived"].mean()

In [29]:
#4. Interpret: Which segment has highest survival likelihood


print("Children had the highest survival",df.groupby("age_group")["survived"].mean())

Children had the highest survival age_group
Child     0.539823
Adult     0.364362
Senior    0.240000
Name: survived, dtype: float64

C:\Users\gk250115\AppData\Local\Temp\ipykernel_14728\2813314333.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print("Children had the highest survival",df.groupby("age_group")["survived"].mean())